package bhw.bihrys.uuid.player;
import bhw.bihrys.uuid.Uuid; import bhw.bihrys.uuid.config.UuidConfig;
import net.minecraft.network.chat.Component; import net.minecraft.server.MinecraftServer; import net.minecraft.server.level.ServerPlayer; import net.minecraft.world.entity.Entity; import net.minecraft.world.entity.TamableAnimal; import net.minecraft.world.level.storage.LevelResource; import net.minecraftforge.event.entity.player.PlayerEvent; import java.io.IOException; import java.nio.file.*; import java.util.*; import java.util.concurrent.ConcurrentLinkedQueue;
public final class PlayerDataManager { private static final Queue<Pending> pending=new ConcurrentLinkedQueue<>(); private PlayerDataManager(){}
 public static void onPlayerLoggedOut(net.minecraft.world.entity.player.Player p){ if(p instanceof ServerPlayer sp){} }
 public static void onServerTick(MinecraftServer s){ Pending x; while((x=pending.poll())!=null) try{apply(s,x.source,x.target,x.by);}catch(Exception e){Uuid.LOGGER.error("UUID swap failed",e);} }
 public static SwapResult requestSwap(MinecraftServer s,UUID source,UUID target,String by){ if(source.equals(target))return SwapResult.fail("源 UUID 和目标 UUID 不能相同"); if(!hasAnyData(s,target))return SwapResult.fail("找不到目标玩家数据"); ServerPlayer p=s.getPlayerList().getPlayer(source); if(p!=null){ p.connection.disconnect(Component.literal("UUID Swap: 请重新进入服务器")); pending.add(new Pending(source,target,by)); return SwapResult.ok("源玩家已断开，数据将在下一 tick 替换"); } try{apply(s,source,target,by);return SwapResult.ok("玩家数据替换完成");}catch(Exception e){return SwapResult.fail(e.getMessage());} }
 private static void apply(MinecraftServer s,UUID source,UUID target,String by)throws IOException{ Path root=s.getWorldPath(LevelResource.ROOT); Path pd=root.resolve("playerdata"), st=root.resolve("stats"), ad=root.resolve("advancements"); if(UuidConfig.INSTANCE.backupBeforeOverwrite) PlayerDataFiles.backup(root.resolve("uuid_backups"),source,target,by(pd.resolve(source+".dat")),pd.resolve(source+".dat"),st.resolve(source+".json"),ad.resolve(source+".json")); PlayerDataFiles.replace(pd.resolve(target+".dat"),pd.resolve(source+".dat"),st.resolve(target+".json"),st.resolve(source+".json"),ad.resolve(target+".json"),ad.resolve(source+".json")); if(UuidConfig.INSTANCE.transferPetsAutomatically) transferLoadedPets(s,target,source); }
 private static String by(Path p){return p.getFileName().toString();}
 public static boolean hasAnyData(MinecraftServer s,UUID u){Path r=s.getWorldPath(LevelResource.ROOT);return PlayerDataFiles.hasAnyData(r.resolve("playerdata").resolve(u+".dat"),r.resolve("stats").resolve(u+".json"),r.resolve("advancements").resolve(u+".json"));}
 public static int transferLoadedPets(MinecraftServer s,UUID oldO,UUID newO){int n=0; for(var l:s.getAllLevels()) for(Entity e:l.getAllEntities()) if(e instanceof TamableAnimal t && t.isTame() && oldO.equals(t.getOwnerUUID())){t.setOwnerUUID(newO);n++;} return n;}
 private record Pending(UUID source,UUID target,String by){} public record SwapResult(boolean success,String message){public static SwapResult ok(String m){return new SwapResult(true,m);}public static SwapResult fail(String m){return new SwapResult(false,m);}}
}
