plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.0.0+1.20.1'
group = 'bhw.bihrys'

base {
    archivesName = 'uuid-forge-1.20.1'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)
sourceSets.main.java.srcDir '../common/src/main/java'

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods {
                uuid {
                    source sourceSets.main
                }
            }
        }
        client {}
        server { args '--nogui' }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.23'
}

tasks.named('processResources', ProcessResources).configure {
    inputs.property 'mod_version', project.version
    filesMatching('META-INF/mods.toml') {
        expand mod_version: project.version
    }
}

tasks.named('jar', Jar).configure {
    from('../LICENSE.txt') {
        rename { "${it}_uuid" }
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}
